-- MySQL Script generated by MySQL Workbench
-- Wed Apr 25 19:03:57 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema api_region_br
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema api_region_br
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `api_region_br` DEFAULT CHARACTER SET utf8 ;
USE `api_region_br` ;

-- -----------------------------------------------------
-- Table `api_region_br`.`STATES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api_region_br`.`STATES` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `initials` VARCHAR(2) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `initials_UNIQUE` (`initials` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `api_region_br`.`CITIES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api_region_br`.`CITIES` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `id_state` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `id_state`),
  INDEX `fk_CITIES_STATES_idx` (`id_state` ASC),
  CONSTRAINT `fk_CITIES_STATES`
    FOREIGN KEY (`id_state`)
    REFERENCES `api_region_br`.`STATES` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
